CC = gcc
CFLAGS = -g

OBJS = combintaionlock
TARGET = combintaionlock

all :$(TARGET)

clean :
	rm -f combintaionlock

$(TARGET) : $(OBJS)
	rm -f  combintaionlock
	$(CC) $(CFLAGS) -o $(OBJS) ./src/main.c
